import type { OriginCity } from '@/components/sections/InboundRelocation';

export const ORIGINS: OriginCity[] = [
  {
    slug: 'new-york',
    city: 'New York',
    state: 'New York',
    stateCode: 'NY',
    distanceMiles: 1084,
    driveDays: '2–3 days',
    twoBedCost: '$4,500–$9,000',
    threeBedCost: '$6,500–$13,000',
    why: [
      'No state income tax — Florida has zero vs New York\u2019s 4–10.9% graduated rate',
      'Lower cost of living — housing ~40% cheaper than NYC metro',
      '260+ sunny days per year — no brutal winters, no shoveling',
      'Major tech, healthcare, and tourism job growth',
      'Lakes, beaches, and theme parks within 90 minutes',
    ],
    weatherNote: 'You\u2019ll never shovel snow again. Summers are hot and humid (90°+ June–September), but winters are 60–75°F. Hurricane season runs June–November — real risk but manageable.',
    taxNote: 'Florida has no state income tax. Save thousands annually. You\u2019ll need to register your vehicle within 30 days (at a Florida DMV) and get a Florida driver\u2019s license within 30 days of establishing residency.',
    tipsLocal: [
      'Get a Florida address established before you file 2026 taxes if possible — can save major state tax',
      'Sell/donate heavy winter clothing before the move — you won\u2019t need it',
      'Book your move 6–8 weeks ahead in May–September; summer is peak',
      'Set up car AC repair in Orlando before summer — you\u2019ll need it',
      'Join Orlando Nextdoor or neighborhood Facebook groups before arriving — best source for local recommendations',
    ],
  },
  {
    slug: 'new-jersey',
    city: 'Northern New Jersey',
    state: 'New Jersey',
    stateCode: 'NJ',
    distanceMiles: 1050,
    driveDays: '2–3 days',
    twoBedCost: '$4,200–$8,600',
    threeBedCost: '$6,200–$12,500',
    why: [
      'Lower property taxes — Florida averages 0.8% vs New Jersey\u2019s 2.5%+',
      'No state income tax — vs New Jersey\u2019s 10.75% top rate',
      'Year-round outdoor weather',
      'Large Jewish, Italian, and Latino communities — cultural familiarity',
      'Direct flights back to NY/NJ from Orlando International (MCO) in 2 hours',
    ],
    weatherNote: 'Goodbye snow days, hello year-round outdoor living. Humidity is real in summer — something you didn\u2019t deal with in Jersey. Hurricane awareness required June–November.',
    taxNote: 'Your property tax bill will drop dramatically. Florida is also a great estate planning state (no estate tax, no inheritance tax). Register vehicle + get FL license within 30 days of residency.',
    tipsLocal: [
      'Sell unnecessary winter items — Florida closets are tighter than NJ basements',
      'Factor humidity into furniture storage decisions — leather and wood furniture can mildew without AC',
      'Downsize snowblowers, heaters, salt storage bins — you\u2019ll never use them again',
      'Book mid-month, mid-week for cheapest rates',
      'Orlando traffic is different — plan around theme park shift changes if you\u2019re near I-4',
    ],
  },
  {
    slug: 'chicago',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    distanceMiles: 1152,
    driveDays: '3 days',
    twoBedCost: '$4,800–$9,500',
    threeBedCost: '$7,000–$13,500',
    why: [
      'No state income tax — vs Illinois\u2019 4.95% flat rate',
      'Escape polar vortex winters — January averages 65°F in Orlando vs 29°F in Chicago',
      'Orlando International flights to O\u2019Hare and Midway daily',
      'Lower cost of living than major Midwest cities',
      'Central location for retirees with family throughout Midwest and South',
    ],
    weatherNote: 'Your definition of "hot" is about to change. Florida summers are brutal — prepare for 92°+ with 85%+ humidity for 4 months straight. Winters are gorgeous (65–75°F). Hurricane risk June–November.',
    taxNote: 'Florida has no state income tax and low property taxes vs Chicago\u2019s high property + income tax combo. Register vehicle and get FL license within 30 days.',
    tipsLocal: [
      'Sell/donate heavy winter coats, boots, snow chains',
      'Book your Orlando movers early — summer moves from Midwest fill up fast',
      'Consider a Penske or U-Haul car trailer if you\u2019re DIY — or use our auto-transport partners',
      'Ship fragile items separately — long Midwest → Florida hauls can be rough on glass and ceramics',
      'Join Orlando Illini or Chicago-expat groups to find familiar community',
    ],
  },
  {
    slug: 'atlanta',
    city: 'Atlanta',
    state: 'Georgia',
    stateCode: 'GA',
    distanceMiles: 438,
    driveDays: '1 day',
    twoBedCost: '$2,800–$5,500',
    threeBedCost: '$4,200–$7,500',
    why: [
      'Closest major metro to Orlando — frequent family visits easy',
      'No state income tax vs Georgia\u2019s 5.39% rate',
      'Warmer winters (Orlando averages 10°+ warmer in January)',
      'Beaches within 60–90 minutes',
      'Tourism, healthcare, and tech job growth',
    ],
    weatherNote: 'You\u2019re used to Southern humidity — but Orlando summers are still more intense than Atlanta. Hurricane season awareness is the biggest shift. Winters are noticeably warmer.',
    taxNote: 'Florida has no state income tax vs Georgia\u2019s 5.39%. Property taxes in both states are comparable. Standard 30-day vehicle + license re-registration.',
    tipsLocal: [
      'This is a 1-day haul — easiest long-distance move on our list',
      'Same-day and next-day Atlanta-to-Orlando moves are doable if you book quickly',
      'I-75 South is the standard route — lots of stops available for comfort breaks',
      'Book weekday moves to avoid Atlanta traffic departure delays',
      'Consider living in Lake Mary or Sanford if you want easy Atlanta commutes — I-4 to I-75 is straightforward',
    ],
  },
  {
    slug: 'boston',
    city: 'Boston',
    state: 'Massachusetts',
    stateCode: 'MA',
    distanceMiles: 1283,
    driveDays: '3 days',
    twoBedCost: '$5,000–$10,000',
    threeBedCost: '$7,500–$14,500',
    why: [
      'No state income tax — vs Massachusetts\u2019 5% flat + surtax on high earners',
      'Dramatic housing cost drop — Orlando homes ~50% less than Boston metro',
      'Escape snow and short winter days',
      'Direct flights to Boston from Orlando International (MCO) in 3 hours',
      'Year-round outdoor quality of life',
    ],
    weatherNote: 'You\u2019ll trade brutal winters for humid summers. Florida summers (June–September) are 90°+ with high humidity. Winters are gorgeous — 65–75°F and sunny.',
    taxNote: 'Major tax savings on both income and property. Florida has no state income tax, no estate tax, and generally lower property taxes. 30-day vehicle + license requirement.',
    tipsLocal: [
      'Sell or donate all winter gear — you won\u2019t need coats, boots, shovels',
      'Book 8+ weeks ahead — Boston → Orlando is a common summer corridor',
      'Consider shipping your car ($1,100–$1,700) and flying — saves the 3-day drive',
      'Orlando traffic differs from Boston — less aggressive, more volume. I-4 is the main artery',
      'If you\u2019re near Boston\u2019s medical/tech sector, Lake Nona\u2019s Medical City + downtown Orlando have direct career parallels',
    ],
  },
  {
    slug: 'philadelphia',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    stateCode: 'PA',
    distanceMiles: 1002,
    driveDays: '2–3 days',
    twoBedCost: '$4,000–$8,200',
    threeBedCost: '$6,000–$12,000',
    why: [
      'No state income tax — vs Pennsylvania\u2019s 3.07% flat',
      'Lower property taxes than Philly suburbs',
      'Warmer winters — Orlando January is 65°F vs Philly\u2019s 35°F',
      'Amtrak and short-flight access back to Philly for family visits',
      'Growing tech, healthcare, and tourism employment',
    ],
    weatherNote: 'No more ice storms or slushy winters. Summers are hotter and more humid than Philly — air conditioning is a year-round necessity. Hurricane season runs June–November.',
    taxNote: 'Florida has no state income tax vs PA\u2019s 3.07%. Property taxes generally lower in Florida. 30-day vehicle + license re-registration after establishing FL residency.',
    tipsLocal: [
      'Sell/donate winter coats, ice scrapers, snow shovels — truly not needed',
      'Book 6+ weeks ahead for Philadelphia-to-Orlando long-distance moves',
      'Consider splitting your move: DIY driving in your own vehicle + pros driving your stuff',
      'Orlando has a large Philadelphia-expat community in Altamonte Springs and Winter Springs',
      'Keep a Pennsylvania-tagged vehicle out of the Orlando sun when possible — PA paint jobs aren\u2019t built for Florida',
    ],
  },
  {
    slug: 'los-angeles',
    city: 'Los Angeles',
    state: 'California',
    stateCode: 'CA',
    distanceMiles: 2503,
    driveDays: '4–5 days',
    twoBedCost: '$7,000–$14,000',
    threeBedCost: '$10,000–$18,000',
    why: [
      'Housing cost — Orlando homes average 60–70% less than comparable LA properties',
      'No state income tax — vs California\u2019s 13.3% top rate',
      'Lower overall cost of living',
      'Year-round warm weather without the drought/wildfire risk',
      'Major film, TV, and theme park industry presence — career continuity possible',
    ],
    weatherNote: 'You\u2019re trading desert dry heat for tropical humidity. Summers are intense (90°+ June–September) but winters are mild and humid (60–75°F). Hurricane season is the biggest environmental shift.',
    taxNote: 'No state income tax in Florida vs up to 13.3% in California. Major tax savings especially on high incomes. Standard 30-day vehicle + license requirement.',
    tipsLocal: [
      'This is a 4–5 day cross-country haul — book 8+ weeks ahead',
      'Consider shipping your car separately ($900–$1,500 LA → Orlando) and flying to meet the truck',
      'Sell/donate anything you don\u2019t truly need — long-haul weight matters more here',
      'Full packing strongly recommended — 2,500+ miles is rough on DIY-packed glass and electronics',
      'If you\u2019re leaving LA for career reasons, Lake Nona (Medical City) and downtown Orlando have thriving tech/creative scenes',
    ],
  },
];
