export const SITE = {
  name: 'Liberty Moves Orlando',
  legalName: 'Liberty Moves Orlando, LLC',
  shortName: 'Liberty Moves',
  url: 'https://libertymovesorlando.com',
  phone: '407-641-2887',
  phoneLink: 'tel:+14076412887',
  phoneDisplay: '(407) 641-2887',
  officePhone: '407-729-9108',
  officePhoneLink: 'tel:+14077299108',
  email: 'libertymovesorlando@gmail.com',
  addressStreet: '3641 S Saint Lucie Dr',
  addressCity: 'Casselberry',
  addressState: 'FL',
  addressZip: '32707',
  usdot: '3455436',
  fldacs: 'IM3347',
  fldacsExpires: '09/30/26',
  reviewCount: 300,
  rating: 5.0,
  googleReviewUrl: 'https://share.google/aY4A57lnhFndH4pEd',
  logo: '/images/logo.png',
  ghl: {
    locationId: '7pnMlJIyNsgtdaD576rT',
    formId: 'RjsFjWPKvuPNDGutFGkb',
    chatWidgetId: '698127e0ed26593e3945a9a5',
    chatWidgetSrc: 'https://widgets.leadconnectorhq.com/loader.js',
    chatResourcesUrl: 'https://widgets.leadconnectorhq.com/chat-widget/loader.js',
    formEmbedSrc: 'https://link.reviveagency.io/js/form_embed.js',
    formIframeSrc: 'https://link.reviveagency.io/widget/form/RjsFjWPKvuPNDGutFGkb',
  },
  gtm: 'GTM-WWLX2D3Q',
} as const;

export type City = {
  slug: string;
  name: string;
  region: string;
  blurb: string;
  zips: string[];
  neighborhoods: string[];
  homeTypes: string;
  priceRange: string;
  distanceFromDowntown: string;
  localNote: string;
};

export const CITIES: City[] = [
  {
    slug: 'winter-park-orlando', name: 'Winter Park', region: 'Orange County',
    blurb: 'Historic, tree-lined, high-value. Our crews know Winter Park homes and buildings inside and out.',
    zips: ['32789', '32792'],
    neighborhoods: ['Olde Winter Park', 'Windsong', 'Virginia Heights', 'Orwin Manor', 'Downtown / Park Avenue'],
    homeTypes: 'Historic bungalows, lakefront estates, downtown condos, mid-century homes',
    priceRange: '$650–$2,400 for most local moves',
    distanceFromDowntown: '5 miles northeast of downtown Orlando',
    localNote: 'Narrow brick streets, mature oak canopy, and Park Avenue parking restrictions mean we plan truck access carefully on every move.',
  },
  {
    slug: 'kissimmee-orlando', name: 'Kissimmee', region: 'Osceola County',
    blurb: 'From downtown Kissimmee to Poinciana, we handle growing-family moves and retirees alike.',
    zips: ['34741', '34743', '34744', '34746', '34747', '34758', '34759'],
    neighborhoods: ['Downtown Kissimmee', 'Poinciana', 'Buenaventura Lakes', 'Celebration border', 'Lake Cecile', 'Four Corners'],
    homeTypes: 'Single-family homes, gated communities, 55+ retirement communities, vacation rentals',
    priceRange: '$600–$2,200 for most local moves',
    distanceFromDowntown: '18 miles south of downtown Orlando',
    localNote: 'Proximity to theme parks means short-term rental turnovers and vacation-home moves are a regular part of our Kissimmee work.',
  },
  {
    slug: 'altamonte-springs-orlando', name: 'Altamonte Springs', region: 'Seminole County',
    blurb: 'Quick I-4 and SR-436 access means faster moves and lower hourly costs for Altamonte Springs residents.',
    zips: ['32701', '32714', '32715'],
    neighborhoods: ['Altamonte Mall area', 'Spring Lake Hills', 'Cranes Roost', 'Eastmonte', 'Bear Lake'],
    homeTypes: 'Apartments, mid-rise condos, single-family homes, 55+ communities',
    priceRange: '$600–$2,100 for most local moves',
    distanceFromDowntown: '10 miles north of downtown Orlando',
    localNote: 'High-rise condo moves in Altamonte typically require elevator reservations — we handle building coordination for you.',
  },
  {
    slug: 'lake-mary-orlando', name: 'Lake Mary', region: 'Seminole County',
    blurb: 'Executive homes and corporate relocations, handled professionally and on-time.',
    zips: ['32746'],
    neighborhoods: ['Heathrow', 'Timacuan', 'Magnolia Plantation', 'Lake Mary Boulevard corridor', 'Griffin Farms'],
    homeTypes: 'Executive single-family homes, luxury gated communities, corporate housing',
    priceRange: '$900–$3,200 for most local moves',
    distanceFromDowntown: '16 miles north of downtown Orlando',
    localNote: 'Lake Mary is a corporate relocation hub — most of our moves here involve executives transferring in or out for work. We coordinate with relocation departments directly.',
  },
  {
    slug: 'apopka-orlando', name: 'Apopka', region: 'Orange County',
    blurb: 'The Indoor Foliage Capital — and home to some of our happiest repeat customers.',
    zips: ['32703', '32712'],
    neighborhoods: ['Rock Springs', 'Errol Estate', 'Wekiva', 'Piedmont Lakes', 'Sweetwater West'],
    homeTypes: 'Single-family homes, farm/acreage properties, new-build communities',
    priceRange: '$650–$2,300 for most local moves',
    distanceFromDowntown: '15 miles northwest of downtown Orlando',
    localNote: 'Apopka’s growth along the 429 corridor means many Apopka moves are from rental-to-new-build or downsizing from larger acreage properties.',
  },
  {
    slug: 'oviedo-orlando', name: 'Oviedo', region: 'Seminole County',
    blurb: 'Family-focused moves with kid- and pet-friendly crews. We get the routine.',
    zips: ['32765', '32766'],
    neighborhoods: ['Twin Rivers', 'Live Oak Reserve', 'Alafaya Woods', 'Oviedo on the Park', 'Carillon'],
    homeTypes: 'Master-planned community homes, townhomes, large single-family homes',
    priceRange: '$700–$2,500 for most local moves',
    distanceFromDowntown: '17 miles northeast of downtown Orlando',
    localNote: 'Oviedo is one of Central Florida’s top-rated school districts — most of our work here is growing families moving into larger homes.',
  },
  {
    slug: 'sanford-orlando', name: 'Sanford', region: 'Seminole County',
    blurb: 'Historic downtown Sanford to the Lake Monroe waterfront — we cover it all.',
    zips: ['32771', '32773'],
    neighborhoods: ['Historic Downtown Sanford', 'Lake Forest', 'Heathrow border', 'Mayfair', 'Riverside'],
    homeTypes: 'Victorian and historic homes, lakefront properties, townhomes, new construction',
    priceRange: '$650–$2,300 for most local moves',
    distanceFromDowntown: '22 miles north of downtown Orlando',
    localNote: 'Historic Sanford homes often have narrow staircases and small doorways — our crews are experienced with antique and heirloom moves here.',
  },
  {
    slug: 'windermere-orlando', name: 'Windermere', region: 'Orange County',
    blurb: 'Luxury-home moves handled with white-glove care. Every piece protected.',
    zips: ['34786'],
    neighborhoods: ['Isleworth', 'Keene’s Pointe', 'Reserve at Lake Butler Sound', 'Windermere Downs', 'Lake Burden'],
    homeTypes: 'Luxury lakefront estates, gated golf communities, multi-million-dollar homes',
    priceRange: '$1,500–$8,000 for most local moves',
    distanceFromDowntown: '15 miles southwest of downtown Orlando',
    localNote: 'Windermere is home to Central Florida’s highest-end real estate. Our Windermere moves include white-glove wrapping, inventoried packing, and art and antique specialists.',
  },
  {
    slug: 'celebration-orlando', name: 'Celebration', region: 'Osceola County',
    blurb: 'HOA-aware scheduling, elevator reservations, narrow-street trucks — we know the drill.',
    zips: ['34747'],
    neighborhoods: ['Downtown Celebration', 'North Village', 'East Village', 'West Village', 'Artisan Park'],
    homeTypes: 'Disney-designed homes, condos, townhomes, artisan craftsman homes',
    priceRange: '$800–$2,800 for most local moves',
    distanceFromDowntown: '25 miles southwest of downtown Orlando',
    localNote: 'Celebration has strict HOA rules for moving trucks, curbside parking, and move hours. We pre-coordinate every Celebration move to keep you compliant.',
  },
  {
    slug: 'st-cloud-orlando', name: 'St. Cloud', region: 'Osceola County',
    blurb: 'Growing community, growing families. We scale up or down to match your move.',
    zips: ['34769', '34771', '34772', '34773'],
    neighborhoods: ['Narcoossee Road corridor', 'Stevens Plantation', 'Narcoossee area', 'Lake Lizzie', 'Anthem Park'],
    homeTypes: 'New-construction single-family homes, master-planned communities, rural acreage',
    priceRange: '$650–$2,400 for most local moves',
    distanceFromDowntown: '26 miles southeast of downtown Orlando',
    localNote: 'St. Cloud is one of the fastest-growing cities in Central Florida, so many of our moves are new-build deliveries. We work with builders on closing-day timing.',
  },
  {
    slug: 'davenport-orlando', name: 'Davenport', region: 'Polk County',
    blurb: 'Short-term rental and vacation-home moves — we understand the unique logistics.',
    zips: ['33837', '33896', '33897'],
    neighborhoods: ['ChampionsGate', 'Reunion', 'Solterra', 'Providence', 'Legacy Park'],
    homeTypes: 'Vacation rental homes, resort-community homes, single-family homes',
    priceRange: '$700–$2,600 for most local moves',
    distanceFromDowntown: '30 miles southwest of downtown Orlando',
    localNote: 'Davenport’s short-term rental industry drives a lot of furniture turnovers and vacation-home moves — we handle both residential relocations and rental-property logistics.',
  },
  {
    slug: 'gotha-orlando', name: 'Gotha', region: 'Orange County',
    blurb: 'Small-town feel, big-city service. Careful handling for estate and antique items.',
    zips: ['34734'],
    neighborhoods: ['Downtown Gotha', 'Windermere border', 'Orange County backroads'],
    homeTypes: 'Historic single-family homes, estate properties, mid-century homes',
    priceRange: '$700–$2,500 for most local moves',
    distanceFromDowntown: '15 miles west of downtown Orlando',
    localNote: 'Gotha is small (population under 2,000) so many moves involve longer-tenure homes with antique furniture, delicate heirlooms, and estate sales.',
  },
  {
    slug: 'montverde-orlando', name: 'Montverde', region: 'Lake County',
    blurb: 'Hillside homes and long driveways — our crews come prepared.',
    zips: ['34756'],
    neighborhoods: ['Bella Collina', 'Sawyer Sound', 'Heron Cay', 'Montverde Academy area'],
    homeTypes: 'Gated luxury homes, hillside estates, lakefront properties',
    priceRange: '$1,000–$3,500 for most local moves',
    distanceFromDowntown: '25 miles west of downtown Orlando',
    localNote: 'Montverde’s hills and long driveways mean we sometimes need shuttle trucks for larger jobs — we scope this during your free estimate.',
  },
  {
    slug: 'winter-garden-orlando', name: 'Winter Garden', region: 'Orange County',
    blurb: 'Downtown District moves and West Orange Trail neighborhoods — done right.',
    zips: ['34787'],
    neighborhoods: ['Downtown Winter Garden', 'Stoneybrook West', 'Hamlin', 'Horizon West', 'Independence'],
    homeTypes: 'Historic downtown homes, new-construction in Horizon West, townhomes',
    priceRange: '$700–$2,500 for most local moves',
    distanceFromDowntown: '14 miles west of downtown Orlando',
    localNote: 'Winter Garden’s Horizon West area is adding thousands of homes per year — we handle many new-construction move-ins with closing-day coordination.',
  },
  {
    slug: 'college-park-orlando', name: 'College Park', region: 'Orange County',
    blurb: 'Historic bungalows and modern condos — we move them all with care.',
    zips: ['32804'],
    neighborhoods: ['Edgewater Drive corridor', 'Ivanhoe Village', 'Lake Adair', 'Lake Highland'],
    homeTypes: 'Historic Craftsman bungalows, mid-century homes, modern condos, downtown lofts',
    priceRange: '$650–$2,100 for most local moves',
    distanceFromDowntown: '3 miles northwest of downtown Orlando',
    localNote: 'College Park’s older homes often have narrow doorways, steep staircases, and tight street parking. Our crews are experienced with vintage-home moves.',
  },
  {
    slug: 'maitland-movers', name: 'Maitland', region: 'Orange County',
    blurb: 'Art & culture district moves — plus the lakeside homes tucked along Lake Lily.',
    zips: ['32751'],
    neighborhoods: ['Lake Lily district', 'Dommerich Estates', 'Lake Minnehaha', 'Maitland Art Center area'],
    homeTypes: 'Lakefront homes, historic single-family, townhomes, condos',
    priceRange: '$650–$2,200 for most local moves',
    distanceFromDowntown: '7 miles north of downtown Orlando',
    localNote: 'Maitland’s Art Center district and lakeside homes mean lots of art, antiques, and specialty items — we bring extra wrapping and care.',
  },
  {
    slug: 'winter-springs-movers', name: 'Winter Springs', region: 'Seminole County',
    blurb: 'Golf-course communities, gated entries, amenity coordination — covered.',
    zips: ['32708'],
    neighborhoods: ['Tuscawilla', 'Highlands', 'Seven Oaks', 'Bear Creek', 'Parkstone'],
    homeTypes: 'Golf-course homes, master-planned communities, townhomes, single-family',
    priceRange: '$700–$2,400 for most local moves',
    distanceFromDowntown: '15 miles northeast of downtown Orlando',
    localNote: 'Tuscawilla and other gated Winter Springs communities require gate-access coordination and HOA notifications — we handle both for you.',
  },
  {
    slug: 'casselberry-movers', name: 'Casselberry', region: 'Seminole County',
    blurb: 'Lakefront and lakeside moves with local crews who know every back road.',
    zips: ['32707', '32730'],
    neighborhoods: ['Lake Howell', 'Lake Kathryn', 'Sausalito', 'Sunset Drive area'],
    homeTypes: 'Lakefront single-family, mid-century homes, condos, townhomes',
    priceRange: '$650–$2,200 for most local moves',
    distanceFromDowntown: '10 miles north of downtown Orlando',
    localNote: 'Casselberry’s many lakes (Howell, Kathryn, Triplet) mean lakeside properties with boat lifts and dock access. We schedule accordingly.',
  },
];

export const SERVICES = [
  { slug: 'residential-moving', title: 'Residential Moving', blurb: 'Homes, apartments, condos — full-service local moves done in a single day.' },
  { slug: 'commercial-moving', title: 'Commercial Moving', blurb: 'Offices, retail, warehouses. Weekend moves to keep your business open.' },
  { slug: 'long-distance-moving', title: 'Long-Distance Moving', blurb: 'Florida to anywhere in the country. Dedicated trucks, transparent pricing.' },
  { slug: 'Packing-Services', title: 'Packing Services', blurb: 'Professional packing and materials. We pack it, we move it, we’re responsible.' },
];

export const NAV_PRIMARY = [
  { href: '/', label: 'Home' },
  { href: '/About-Us', label: 'About' },
  { href: '/residential-moving', label: 'Residential' },
  { href: '/commercial-moving', label: 'Commercial' },
  { href: '/long-distance-moving', label: 'Long Distance' },
  { href: '/Packing-Services', label: 'Packing' },
  { href: '/orlando-moving-cost', label: 'Pricing' },
  { href: '/Why-Choose-Us', label: 'Why Us' },
  { href: '/faqs', label: 'FAQs' },
  { href: '/blog', label: 'Blog' },
  { href: '/contact-us', label: 'Contact' },
];
