// AUTO-GENERATED by scripts/generate-blog-manifest.mjs — do not edit by hand.
// Runs on `npm run prebuild` (and therefore on every Vercel build), enumerating
// src/data/generated-blog-posts/. Add a post by committing its JSON; the import
// lines below are rewritten for you.
//
// Static imports are intentional: they guarantee every JSON is bundled into each
// consuming serverless function.

import post0_apartmentMovingInOrlandoWhatNobodyTellsY from './generated-blog-posts/apartment-moving-in-orlando-what-nobody-tells-you-before-move-in-day.json';
import post1_bestMoversInOrlandoForSummer2026WhatToLo from './generated-blog-posts/best-movers-in-orlando-for-summer-2026-what-to-look-for-before-you-book.json';
import post2_howToChooseTheBestMovingCompanyInOrlando from './generated-blog-posts/how-to-choose-the-best-moving-company-in-orlando-without-getting-burned-by.json';
import post3_movingToCasselberryFlHereSWhatOrlandoFam from './generated-blog-posts/moving-to-casselberry-fl-here-s-what-orlando-families-need-to-know-before-hiring-movers.json';
import post4_movingWithKidsInOrlandoHowToMakeTheTrans from './generated-blog-posts/moving-with-kids-in-orlando-how-to-make-the-transition-easier-for-the-whole-fami.json';
import post5_orlandoApartmentMoveChecklist30DayPlan from './generated-blog-posts/orlando-apartment-move-checklist-30-day-plan.json';
import post6_theRealCostOfHiringTheWrongMoversInOrlan from './generated-blog-posts/the-real-cost-of-hiring-the-wrong-movers-in-orlando-and-how-to-avoid-it.json';
import post7_whyLibertyMovesOrlandoIsOneOfTheTopMover from './generated-blog-posts/why-liberty-moves-orlando-is-one-of-the-top-movers-in-lake-mary.json';

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  metaDescription?: string;
  category: string;
  readTime: string;
  date: string;
  isoDate: string;
  author: string;
  tags: string[];
  heroImage?: string;
  heroImageAlt?: string;
  contentHtml?: string;
  contentBlocks?: string[];
}

const ALL: BlogPost[] = [
  post0_apartmentMovingInOrlandoWhatNobodyTellsY as BlogPost,
  post1_bestMoversInOrlandoForSummer2026WhatToLo as BlogPost,
  post2_howToChooseTheBestMovingCompanyInOrlando as BlogPost,
  post3_movingToCasselberryFlHereSWhatOrlandoFam as BlogPost,
  post4_movingWithKidsInOrlandoHowToMakeTheTrans as BlogPost,
  post5_orlandoApartmentMoveChecklist30DayPlan as BlogPost,
  post6_theRealCostOfHiringTheWrongMoversInOrlan as BlogPost,
  post7_whyLibertyMovesOrlandoIsOneOfTheTopMover as BlogPost,
];

export const BLOG_POSTS: Record<string, BlogPost> = Object.fromEntries(
  ALL.map((p) => [p.slug, p]),
);

export function getBlogPost(slug: string): BlogPost | null {
  return BLOG_POSTS[slug] ?? null;
}

export function listBlogPosts(): BlogPost[] {
  return ALL;
}
